### ISSUE TITLE
Проблема с установкой через pip

### ISSUE THREAD

**Issue by licensedtroubleshooter** [bond005/seq2seq#1]
При установке через pip install вместо того чтобы автоматически устанавливать зависимости, установка прерывается по исключению.

**Comment by euxsun** [comment]
Problem still pertains: 
```
Collecting seq2seq_lstm
  Downloading seq2seq-lstm-0.1.6.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_hxyw4_r/seq2seq-lstm_572758f58f5243fdb13b89f0bbc4fd03/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_hxyw4_r/seq2seq-lstm_572758f58f5243fdb13b89f0bbc4fd03/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_r5drx5e
         cwd: /tmp/pip-install-_hxyw4_r/seq2seq-lstm_572758f58f5243fdb13b89f0bbc4fd03/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_hxyw4_r/seq2seq-lstm_572758f58f5243fdb13b89f0bbc4fd03/setup.py", line 5, in <module>
        import seq2seq_lstm
      File "/tmp/pip-install-_hxyw4_r/seq2seq-lstm_572758f58f5243fdb13b89f0bbc4fd03/seq2seq_lstm/__init__.py", line 3, in <module>
        from .seq2seq_lstm import Seq2SeqLSTM
      File "/tmp/pip-install-_hxyw4_r/seq2seq-lstm_572758f58f5243fdb13b89f0bbc4fd03/seq2seq_lstm/seq2seq_lstm.py", line 26, in <module>
        import tensorflow.keras.backend as K
    ModuleNotFoundError: No module named 'tensorflow'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/87/29a7d393d953fc1f66d6af1edd13c19608046c818b68a060948372357ce5/seq2seq-lstm-0.1.6.tar.gz#sha256=8306d74474f160fb35bad046dd00a97f6019e7fb0ad12f53eae9554dfbc2ca30 (from https://pypi.org/simple/seq2seq-lstm/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
